
loom.ignoreDependencyLoomVersionValidation = true
loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false
org.gradle.jvmargs=-Xmx4096M
org.gradle.parallel=true
org.gradle.daemon = false

# Mc stuff
minecraft_version = 1.21.1
minecraft_min_version = 1.21
minecraft_max_version = 1.22

enabled_platforms = fabric,neoforge
pack_format_number = 20

# Mod stuff
mod_id = jeed
mod_name = Just Enough Effects Descriptions
mod_version = 1.21-2.3.0
mod_license = GLP3
mod_group_id = net.mehvahdjukaar
mod_authors = MehVahdJukaar
mod_description = REI/JEI/EMI addon that shows effects and their descriptions
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed
mod_github = https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions
mod_credits = MehVahdJukaar, Plantkillable

project_id = 532286


# Loaders

parchment_version = 1.21:2024.07.28

fabric_loader_version = 0.16.3
fabric_api_version = 0.103.0+1.21.1

neo_version = 21.1.90
neo_version_range = [4,)
loader_version_range = [4,)

modmenu_version = 11.0.0




