# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false
fabric.loom.ignoreDependencyLoomVersionValidation = true
fabric.loom.allowMismatchedPlatformVersions = true
fabric.loom.multiProjectOptimisation = false

# Project
mod_id = jeed
mod_name = Just Enough Effects Descriptions
mod_version = 1.21-2.3.4
mod_author = MehVahdJukaar
mod_description = REI/JEI/EMI addon that shows effects and their descriptions
mod_license = GLP3
mod_authors = MehVahdJukaar
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed
mod_credits = MehVahdJukaar, Plantkillable
mod_github = https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions

release_type = release
maven_group = net.mehvahdjukaar

# Publishing
repository = MehVahdJukaar/JustEnoughEffectDescriptions
modrinth_project_id = just-enough-effect-descriptions-jeed
curseforge_project_id = 532286

# MC / loader versions
mc_version = 1.21.1

neoforge_version = 21.1.228

fabric_loader_version = 0.17.2
fabric_api_version = 0.116.6+1.21.1

parchment_mappings_version = 2024.11.17
