# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true
org.gradle.daemon = false

# Project
mod_id = jeed
mod_name = Just Enough Effects Descriptions
mod_version = 1.21.11-2.4.2
mod_author = MehVahdJukaar
mod_description = REI/JEI/EMI addon that shows effects and their descriptions
mod_license = GLP3
mod_authors = MehVahdJukaar
mod_homepage = https://www.curseforge.com/minecraft/mc-mods/just-enough-effect-descriptions-jeed
mod_credits = MehVahdJukaar, Plantkillable
mod_github = https://github.com/MehVahdJukaar/JustEnoughEffectDescriptions
mod_environment = client

release_type = release
maven_group = net.mehvahdjukaar


# Publishing
repository = MehVahdJukaar/JustEnoughEffectDescriptions
modrinth_project_id = just-enough-effect-descriptions-jeed
curseforge_project_id = 532286

mc_version = 1.21.11

neoforge_version = 21.11.44

fabric_api_version = 0.141.5+1.21.11
fabric_loader_version = 0.19.3


# Recipe viewers
jei_version = 27.17.0.52
rei_version = 21.11.816
