architectury {
    common(enabled_platforms.split(",")) {
        // This means map neoforge to forge
        //it.platformPackage "neoforge", "forge"
    }
}

loom {
    accessWidenerPath = file("src/main/resources/jeed.accesswidener")
}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"

    modCompileOnly "me.shedaniel:REIPluginCompatibilities-forge-annotations:9.+"

    modCompileOnly("curse.maven:jei-238222:5846880")
    modCompileOnly("curse.maven:emi-580555:5436759")
    //modCompileOnly("curse.maven:roughly-enough-items-310111:5435024")
    modCompileOnly "me.shedaniel:RoughlyEnoughItems-neoforge:16.0.729"

    //modCompileOnly "dev.emi:emi-xplat-intermediary:1.1.7+${rootProject.minecraft_version}"
}

publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}
